Update project-setup.md
features without brackets causes the following issue:
```
error: failed to parse manifest at `/home/anton/code/core-dump-daemon/Cargo.toml`

Caused by:
  invalid type: string "testkit", expected a sequence for key `dev-dependencies.roperator.features`
```
This patch resolves it.